apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: haproxy
  namespace: haproxy
spec:
  controller: haproxy-ingress.github.io/controller
  parameters:
    kind: ConfigMap
    name: haproxy
