apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: guestbook-ui
  namespace: guestbook
spec:
  rules:
  - host: 51.38.223.52
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook-ui
            port:
              number: 80
