apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ingress/cert-manager
    repoURL: https://github.com/batleforc/poc-argocd.git
    targetRevision: HEAD
